### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by SteelAlloy** [grasilife/github-pages-deploy-action#1]
**Describe the bug**

Build and deploy fail

**Reproduce**

```
Run grasilife/github-pages-deploy-action@master
  env:
    ACCESS_TOKEN: ***
    BASE_BRANCH: master
    BRANCH: gh-pages
    FOLDER: build
    CNAME: www.secure-rm.com
    BUILD_SCRIPT: npm install && npm run build
/usr/bin/docker run --name e87b5279380b952cd04ce98f657105bb99907a_3a657a --label e87b52 --workdir /github/workspace --rm -e ACCESS_TOKEN -e BASE_BRANCH -e BRANCH -e FOLDER -e CNAME -e BUILD_SCRIPT -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/docs/docs":"/github/workspace" e87b52:79380b952cd04ce98f657105bb99907a
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Expected behavior**

Here is my file, am I doing things wrong?

```yaml
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: grasilife/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
        CNAME: www.secure-rm.com
        BUILD_SCRIPT: npm install && npm run build # The build script the action should run prior to deploying.
```
